FROM python:3.10

WORKDIR /user-api

COPY ./requirements.txt /user-api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /user-api/requirements.txt

COPY . /user-api/

CMD ["uvicorn","main:app", "--reload" ]