FROM python:3.10

WORKDIR /xml-api

COPY ./requirements.txt /xml-api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /xml-api/requirements.txt

COPY . /xml-api/

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]